- include_role:
    name: geerlingguy.git

- include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: '{{workstation_user.username}}'
        oh_my_zsh:
          theme: bureau
          plugins:
            - git