- include_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username: '{{workstation_user.username}}'
        visual_studio_code_settings_force_overwrite: yes
        visual_studio_code_settings:
          editor.rulers: [80, 100, 120]
          editor.renderWhitespace: all
          editor.tabSize: 2
          files.trimTrailingWhitespace: true